### ISSUE TITLE
SlackNotifier Fails - ParameterNotFound

### ISSUE THREAD

**Issue by ngumina** [aws-solutions/aws-limit-monitor#90]
I am trying to run the slack notifier lambda and receiving the below error

{
  "message": null,
  "code": "ParameterNotFound",
  "time": "2022-07-22T16:01:14.668Z",
  "requestId": "7cccce00-4243-44c6-b919-b7a20da6c7bc",
  "statusCode": 400,
  "retryable": false,
  "retryDelay": 78.1743234637905
}

the environment variables for the function are set correctly and the parameters are stored/named correctly in SSM parameter store as well. Please advise

![image](https://user-images.githubusercontent.com/48841129/180478991-a8a6aa18-45fb-4dec-8b09-9f69b5392843.png)

![image](https://user-images.githubusercontent.com/48841129/180478868-e4eb0d6a-3a40-42a6-b272-75938cee7a76.png)

**Comment by ngumina** [comment]
Full stacktrace

<html>
<body>


2022-07-22T15:58:55.954Z	fa8a8baf-7e06-4ea7-8877-08a865d770e6	INFO	[ERROR]ParameterNotFound: null    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) | 2022-07-22T15:58:55.954Z fa8a8baf-7e06-4ea7-8877-08a865d770e6 INFO [ERROR]ParameterNotFound: null at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14) at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10) at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12) at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10 at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9) at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
-- | --



</body>
</html>
